name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: zephyr-microui

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install SDL2 libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr-microui
          toolchains: arm-zephyr-eabi:x86_64-zephyr-elf

      - name: Build samples
        working-directory: zephyr-microui
        shell: bash
        run: |
          west twister -T samples -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      - name: Twister Tests
        working-directory: zephyr-microui
        shell: bash
        run: |
          west twister -T tests -v --inline-logs --jobs 1 --integration $EXTRA_TWISTER_FLAGS
